name = "image-generation"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "media"

[[r2_buckets]]
binding = "USER_MEDIA_BUCKET"
bucket_name = "user-media"

[[d1_databases]]
binding = "IMAGE_DB"
database_name = "tiko-image-generation"
database_id = "ab7cdbd1-e50a-4862-b8eb-681d263c3f66"

[[d1_databases]]
binding = "IDENTITY_DB"
database_name = "tiko-identity"
database_id = "036a1726-ac16-48a9-ab76-22c3a88ca7ae"

[[kv_namespaces]]
binding = "IDENTITY_SESSION_CACHE"
id = "32bcc7c6d5074a95a1ea62ee772da3be"
preview_id = "32bcc7c6d5074a95a1ea62ee772da3be"

[vars]
ENVIRONMENT = "development"

[env.production]
name = "image-generation"
route = { pattern = "generate.tikocdn.org/*", zone_name = "tikocdn.org" }

[[env.production.r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "media"

[[env.production.r2_buckets]]
binding = "USER_MEDIA_BUCKET"
bucket_name = "user-media"

[[env.production.d1_databases]]
binding = "IMAGE_DB"
database_name = "tiko-image-generation"
database_id = "ab7cdbd1-e50a-4862-b8eb-681d263c3f66"

[[env.production.d1_databases]]
binding = "IDENTITY_DB"
database_name = "tiko-identity"
database_id = "036a1726-ac16-48a9-ab76-22c3a88ca7ae"

[[env.production.kv_namespaces]]
binding = "IDENTITY_SESSION_CACHE"
id = "32bcc7c6d5074a95a1ea62ee772da3be"
preview_id = "32bcc7c6d5074a95a1ea62ee772da3be"

[env.production.vars]
ENVIRONMENT = "production"

# Analytics Engine - uncomment after enabling in dashboard
# [[analytics_engine_datasets]]
# binding = "ANALYTICS"

# Secrets to be set via wrangler secret:
# - OPENAI_API_KEY
