name = "tiko-dev-app-router"
main = "src/index.ts"
compatibility_date = "2025-08-03"
account_id = "dc2b7d14a69351375cab6de9a13ddee9"

routes = [
  { pattern = "dev.yesno.tikoapps.org/*", zone_name = "tikoapps.org" },
  { pattern = "dev.type.tikoapps.org/*", zone_name = "tikoapps.org" },
  { pattern = "dev.todo.tikoapps.org/*", zone_name = "tikoapps.org" },
  { pattern = "dev.cards.tikoapps.org/*", zone_name = "tikoapps.org" },
  { pattern = "dev.clock.tikoapps.org/*", zone_name = "tikoapps.org" },
  { pattern = "dev.timer.tikoapps.org/*", zone_name = "tikoapps.org" },
  { pattern = "dev.radio.tikoapps.org/*", zone_name = "tikoapps.org" },
  { pattern = "dev.sequence.tikoapps.org/*", zone_name = "tikoapps.org" }
]
