name = "i18n-data"
main = "src/index.ts"
compatibility_date = "2024-05-07"
account_id = "dc2b7d14a69351375cab6de9a13ddee9"

[vars]
LEZU_PROJECT_ID = "project_a2a9847c-edbd-499e-874f-5a58c0cca80c"
LEZU_API_BASE = "https://api.lezu.app"

[env.production]
vars = { ENVIRONMENT = "production", LEZU_PROJECT_ID = "project_a2a9847c-edbd-499e-874f-5a58c0cca80c", LEZU_API_BASE = "https://api.lezu.app" }

# Required secret:
# LEZU_API_KEY - Set via: wrangler secret put LEZU_API_KEY