name = "i18n-data"
main = "src/index.ts"
compatibility_date = "2024-05-07"

[env.production]
vars = { ENVIRONMENT = "production" }

# Environment variables (to be set via wrangler secret)
# SUPABASE_URL - The Supabase project URL
# SUPABASE_SERVICE_KEY - The Supabase service role key

# To set secrets:
# wrangler secret put SUPABASE_URL
# wrangler secret put SUPABASE_SERVICE_KEY