name = "tts-generation"
main = "src/index.ts"
compatibility_date = "2024-12-14"

# Custom domain for TTS worker
routes = [
  { pattern = "https://tts.tikoapi.org/*", zone_name = "tikoapi.org" }
]

[env.production]
vars = { ENVIRONMENT = "production" }

[[r2_buckets]]
binding = "AUDIO_BUCKET"
bucket_name = "tiko-tts-audio"
preview_bucket_name = "tiko-tts-audio-preview"

[vars]
ENVIRONMENT = "development"

# Secrets to be set:
# OPENAI_API_KEY - Your OpenAI API key
# SUPABASE_URL - Supabase project URL  
# SUPABASE_SERVICE_KEY - Supabase service role key