name = "user-removal"
main = "src/index.ts"
compatibility_date = "2023-12-01"

[env.production]
route = { pattern = "tikoapi.org/user-removal/*", zone_name = "tikoapi.org" }

[[env.production.kv_namespaces]]
binding = "USER_REMOVAL_LOG"
id = "your_kv_namespace_id"

[vars]
ENVIRONMENT = "production"

# Secrets (set via wrangler secret put)
# VITE_SUPABASE_URL - Supabase project URL
# VITE_SUPABASE_SERVICE_KEY - Supabase service role key (for admin operations)
# ADMIN_API_KEY - Secret key for admin operations