#!/usr/bin/env node

const fs = require('fs')
const path = require('path')

// This would normally use a translation API like Google Translate or DeepL
// For now, I'll provide some common translations for key UI terms

const translations = {
  bg: { // Bulgarian
    // Common
    'save': 'Запази',
    'cancel': 'Отказ',
    'delete': 'Изтрий',
    'edit': 'Редактирай',
    'close': 'Затвори',
    'loading': 'Зареждане...',
    'error': 'Грешка',
    'success': 'Успех',
    'warning': 'Предупреждение',
    'confirm': 'Потвърди',
    'yes': 'Да',
    'no': 'Не',
    'settings': 'Настройки',
    'back': 'Назад',
    'home': 'Начало',
    'done': 'Готово',
    'add': 'Добави',
    'remove': 'Премахни',
    'reset': 'Нулирай',
    'apply': 'Приложи',
    'search': 'Търси',
    'filter': 'Филтър',
    'sort': 'Сортирай',
    'refresh': 'Опресни',
    'upload': 'Качи',
    'download': 'Изтегли',
    'share': 'Сподели',
    'copy': 'Копирай',
    'paste': 'Постави',
    'undo': 'Отмени',
    'redo': 'Повтори',
    // Add more translations...
  },
  cs: { // Czech
    'save': 'Uložit',
    'cancel': 'Zrušit',
    'delete': 'Smazat',
    'edit': 'Upravit',
    'close': 'Zavřít',
    'loading': 'Načítání...',
    'error': 'Chyba',
    'success': 'Úspěch',
    'warning': 'Varování',
    'confirm': 'Potvrdit',
    'yes': 'Ano',
    'no': 'Ne',
    'settings': 'Nastavení',
    'back': 'Zpět',
    'home': 'Domů',
    'done': 'Hotovo',
    'add': 'Přidat',
    'remove': 'Odebrat',
    'reset': 'Obnovit',
    'apply': 'Použít',
    'search': 'Hledat',
    'filter': 'Filtr',
    'sort': 'Seřadit',
    'refresh': 'Obnovit',
    'upload': 'Nahrát',
    'download': 'Stáhnout',
    'share': 'Sdílet',
    'copy': 'Kopírovat',
    'paste': 'Vložit',
    'undo': 'Zpět',
    'redo': 'Znovu',
  },
  da: { // Danish
    'save': 'Gem',
    'cancel': 'Annuller',
    'delete': 'Slet',
    'edit': 'Rediger',
    'close': 'Luk',
    'loading': 'Indlæser...',
    'error': 'Fejl',
    'success': 'Succes',
    'warning': 'Advarsel',
    'confirm': 'Bekræft',
    'yes': 'Ja',
    'no': 'Nej',
    'settings': 'Indstillinger',
    'back': 'Tilbage',
    'home': 'Hjem',
    'done': 'Færdig',
    'add': 'Tilføj',
    'remove': 'Fjern',
    'reset': 'Nulstil',
    'apply': 'Anvend',
    'search': 'Søg',
    'filter': 'Filter',
    'sort': 'Sorter',
    'refresh': 'Opdater',
    'upload': 'Upload',
    'download': 'Download',
    'share': 'Del',
    'copy': 'Kopier',
    'paste': 'Indsæt',
    'undo': 'Fortryd',
    'redo': 'Gentag',
  },
  et: { // Estonian
    'save': 'Salvesta',
    'cancel': 'Tühista',
    'delete': 'Kustuta',
    'edit': 'Muuda',
    'close': 'Sulge',
    'loading': 'Laadimine...',
    'error': 'Viga',
    'success': 'Õnnestus',
    'warning': 'Hoiatus',
    'confirm': 'Kinnita',
    'yes': 'Jah',
    'no': 'Ei',
    'settings': 'Seaded',
    'back': 'Tagasi',
    'home': 'Avaleht',
    'done': 'Valmis',
    'add': 'Lisa',
    'remove': 'Eemalda',
    'reset': 'Lähtesta',
    'apply': 'Rakenda',
    'search': 'Otsi',
    'filter': 'Filter',
    'sort': 'Sorteeri',
    'refresh': 'Värskenda',
    'upload': 'Laadi üles',
    'download': 'Laadi alla',
    'share': 'Jaga',
    'copy': 'Kopeeri',
    'paste': 'Kleebi',
    'undo': 'Võta tagasi',
    'redo': 'Tee uuesti',
  },
  fi: { // Finnish
    'save': 'Tallenna',
    'cancel': 'Peruuta',
    'delete': 'Poista',
    'edit': 'Muokkaa',
    'close': 'Sulje',
    'loading': 'Ladataan...',
    'error': 'Virhe',
    'success': 'Onnistui',
    'warning': 'Varoitus',
    'confirm': 'Vahvista',
    'yes': 'Kyllä',
    'no': 'Ei',
    'settings': 'Asetukset',
    'back': 'Takaisin',
    'home': 'Koti',
    'done': 'Valmis',
    'add': 'Lisää',
    'remove': 'Poista',
    'reset': 'Nollaa',
    'apply': 'Käytä',
    'search': 'Hae',
    'filter': 'Suodata',
    'sort': 'Lajittele',
    'refresh': 'Päivitä',
    'upload': 'Lataa',
    'download': 'Lataa',
    'share': 'Jaa',
    'copy': 'Kopioi',
    'paste': 'Liitä',
    'undo': 'Kumoa',
    'redo': 'Tee uudelleen',
  },
  ga: { // Irish
    'save': 'Sábháil',
    'cancel': 'Cealaigh',
    'delete': 'Scrios',
    'edit': 'Cuir in eagar',
    'close': 'Dún',
    'loading': 'Ag lódáil...',
    'error': 'Earráid',
    'success': 'D\'éirigh leis',
    'warning': 'Rabhadh',
    'confirm': 'Deimhnigh',
    'yes': 'Tá',
    'no': 'Níl',
    'settings': 'Socruithe',
    'back': 'Ar ais',
    'home': 'Baile',
    'done': 'Déanta',
    'add': 'Cuir leis',
    'remove': 'Bain',
    'reset': 'Athshocraigh',
    'apply': 'Cuir i bhfeidhm',
    'search': 'Cuardaigh',
    'filter': 'Scagaire',
    'sort': 'Sórtáil',
    'refresh': 'Athnuaigh',
    'upload': 'Uaslódáil',
    'download': 'Íoslódáil',
    'share': 'Comhroinn',
    'copy': 'Cóipeáil',
    'paste': 'Greamaigh',
    'undo': 'Cealaigh',
    'redo': 'Athdhéan',
  },
  hr: { // Croatian
    'save': 'Spremi',
    'cancel': 'Odustani',
    'delete': 'Izbriši',
    'edit': 'Uredi',
    'close': 'Zatvori',
    'loading': 'Učitavanje...',
    'error': 'Greška',
    'success': 'Uspjeh',
    'warning': 'Upozorenje',
    'confirm': 'Potvrdi',
    'yes': 'Da',
    'no': 'Ne',
    'settings': 'Postavke',
    'back': 'Natrag',
    'home': 'Početna',
    'done': 'Gotovo',
    'add': 'Dodaj',
    'remove': 'Ukloni',
    'reset': 'Poništi',
    'apply': 'Primijeni',
    'search': 'Traži',
    'filter': 'Filter',
    'sort': 'Sortiraj',
    'refresh': 'Osvježi',
    'upload': 'Prenesi',
    'download': 'Preuzmi',
    'share': 'Podijeli',
    'copy': 'Kopiraj',
    'paste': 'Zalijepi',
    'undo': 'Poništi',
    'redo': 'Ponovi',
  },
  hu: { // Hungarian
    'save': 'Mentés',
    'cancel': 'Mégse',
    'delete': 'Törlés',
    'edit': 'Szerkesztés',
    'close': 'Bezárás',
    'loading': 'Betöltés...',
    'error': 'Hiba',
    'success': 'Sikeres',
    'warning': 'Figyelmeztetés',
    'confirm': 'Megerősítés',
    'yes': 'Igen',
    'no': 'Nem',
    'settings': 'Beállítások',
    'back': 'Vissza',
    'home': 'Kezdőlap',
    'done': 'Kész',
    'add': 'Hozzáadás',
    'remove': 'Eltávolítás',
    'reset': 'Visszaállítás',
    'apply': 'Alkalmaz',
    'search': 'Keresés',
    'filter': 'Szűrő',
    'sort': 'Rendezés',
    'refresh': 'Frissítés',
    'upload': 'Feltöltés',
    'download': 'Letöltés',
    'share': 'Megosztás',
    'copy': 'Másolás',
    'paste': 'Beillesztés',
    'undo': 'Visszavonás',
    'redo': 'Ismét',
  },
  lt: { // Lithuanian
    'save': 'Išsaugoti',
    'cancel': 'Atšaukti',
    'delete': 'Ištrinti',
    'edit': 'Redaguoti',
    'close': 'Uždaryti',
    'loading': 'Kraunama...',
    'error': 'Klaida',
    'success': 'Sėkmė',
    'warning': 'Įspėjimas',
    'confirm': 'Patvirtinti',
    'yes': 'Taip',
    'no': 'Ne',
    'settings': 'Nustatymai',
    'back': 'Atgal',
    'home': 'Pradžia',
    'done': 'Atlikta',
    'add': 'Pridėti',
    'remove': 'Pašalinti',
    'reset': 'Atstatyti',
    'apply': 'Taikyti',
    'search': 'Ieškoti',
    'filter': 'Filtras',
    'sort': 'Rūšiuoti',
    'refresh': 'Atnaujinti',
    'upload': 'Įkelti',
    'download': 'Atsisiųsti',
    'share': 'Dalintis',
    'copy': 'Kopijuoti',
    'paste': 'Įklijuoti',
    'undo': 'Atšaukti',
    'redo': 'Pakartoti',
  },
  lv: { // Latvian
    'save': 'Saglabāt',
    'cancel': 'Atcelt',
    'delete': 'Dzēst',
    'edit': 'Rediģēt',
    'close': 'Aizvērt',
    'loading': 'Ielādē...',
    'error': 'Kļūda',
    'success': 'Veiksmīgi',
    'warning': 'Brīdinājums',
    'confirm': 'Apstiprināt',
    'yes': 'Jā',
    'no': 'Nē',
    'settings': 'Iestatījumi',
    'back': 'Atpakaļ',
    'home': 'Sākums',
    'done': 'Gatavs',
    'add': 'Pievienot',
    'remove': 'Noņemt',
    'reset': 'Atiestatīt',
    'apply': 'Pielietot',
    'search': 'Meklēt',
    'filter': 'Filtrs',
    'sort': 'Kārtot',
    'refresh': 'Atsvaidzināt',
    'upload': 'Augšupielādēt',
    'download': 'Lejupielādēt',
    'share': 'Dalīties',
    'copy': 'Kopēt',
    'paste': 'Ielīmēt',
    'undo': 'Atsaukt',
    'redo': 'Atkārtot',
  },
  no: { // Norwegian
    'save': 'Lagre',
    'cancel': 'Avbryt',
    'delete': 'Slett',
    'edit': 'Rediger',
    'close': 'Lukk',
    'loading': 'Laster...',
    'error': 'Feil',
    'success': 'Suksess',
    'warning': 'Advarsel',
    'confirm': 'Bekreft',
    'yes': 'Ja',
    'no': 'Nei',
    'settings': 'Innstillinger',
    'back': 'Tilbake',
    'home': 'Hjem',
    'done': 'Ferdig',
    'add': 'Legg til',
    'remove': 'Fjern',
    'reset': 'Tilbakestill',
    'apply': 'Bruk',
    'search': 'Søk',
    'filter': 'Filter',
    'sort': 'Sorter',
    'refresh': 'Oppdater',
    'upload': 'Last opp',
    'download': 'Last ned',
    'share': 'Del',
    'copy': 'Kopier',
    'paste': 'Lim inn',
    'undo': 'Angre',
    'redo': 'Gjør om',
  },
  ro: { // Romanian
    'save': 'Salvează',
    'cancel': 'Anulează',
    'delete': 'Șterge',
    'edit': 'Editează',
    'close': 'Închide',
    'loading': 'Se încarcă...',
    'error': 'Eroare',
    'success': 'Succes',
    'warning': 'Avertisment',
    'confirm': 'Confirmă',
    'yes': 'Da',
    'no': 'Nu',
    'settings': 'Setări',
    'back': 'Înapoi',
    'home': 'Acasă',
    'done': 'Gata',
    'add': 'Adaugă',
    'remove': 'Elimină',
    'reset': 'Resetează',
    'apply': 'Aplică',
    'search': 'Caută',
    'filter': 'Filtru',
    'sort': 'Sortează',
    'refresh': 'Reîmprospătează',
    'upload': 'Încarcă',
    'download': 'Descarcă',
    'share': 'Distribuie',
    'copy': 'Copiază',
    'paste': 'Lipește',
    'undo': 'Anulează',
    'redo': 'Refă',
  },
  sk: { // Slovak
    'save': 'Uložiť',
    'cancel': 'Zrušiť',
    'delete': 'Vymazať',
    'edit': 'Upraviť',
    'close': 'Zavrieť',
    'loading': 'Načítava sa...',
    'error': 'Chyba',
    'success': 'Úspech',
    'warning': 'Upozornenie',
    'confirm': 'Potvrdiť',
    'yes': 'Áno',
    'no': 'Nie',
    'settings': 'Nastavenia',
    'back': 'Späť',
    'home': 'Domov',
    'done': 'Hotovo',
    'add': 'Pridať',
    'remove': 'Odstrániť',
    'reset': 'Obnoviť',
    'apply': 'Použiť',
    'search': 'Hľadať',
    'filter': 'Filter',
    'sort': 'Zoradiť',
    'refresh': 'Obnoviť',
    'upload': 'Nahrať',
    'download': 'Stiahnuť',
    'share': 'Zdieľať',
    'copy': 'Kopírovať',
    'paste': 'Prilepiť',
    'undo': 'Späť',
    'redo': 'Znova',
  },
  sl: { // Slovenian
    'save': 'Shrani',
    'cancel': 'Prekliči',
    'delete': 'Izbriši',
    'edit': 'Uredi',
    'close': 'Zapri',
    'loading': 'Nalaganje...',
    'error': 'Napaka',
    'success': 'Uspeh',
    'warning': 'Opozorilo',
    'confirm': 'Potrdi',
    'yes': 'Da',
    'no': 'Ne',
    'settings': 'Nastavitve',
    'back': 'Nazaj',
    'home': 'Domov',
    'done': 'Končano',
    'add': 'Dodaj',
    'remove': 'Odstrani',
    'reset': 'Ponastavi',
    'apply': 'Uporabi',
    'search': 'Išči',
    'filter': 'Filter',
    'sort': 'Razvrsti',
    'refresh': 'Osveži',
    'upload': 'Naloži',
    'download': 'Prenesi',
    'share': 'Deli',
    'copy': 'Kopiraj',
    'paste': 'Prilepi',
    'undo': 'Razveljavi',
    'redo': 'Ponovi',
  },
}

// Read the English file to get all keys
const enPath = path.join(__dirname, '../packages/ui/src/i18n/locales/base/en.ts')
const enContent = fs.readFileSync(enPath, 'utf8')

// Function to translate a file
function translateFile(language, languageName) {
  const filePath = path.join(__dirname, `../packages/ui/src/i18n/locales/base/${language}.ts`)
  
  if (!fs.existsSync(filePath)) {
    console.log(`⚠️  ${languageName} (${language}.ts) does not exist`)
    return
  }
  
  let content = fs.readFileSync(filePath, 'utf8')
  const langTranslations = translations[language] || {}
  let changeCount = 0
  
  // Replace English values with translations where available
  Object.entries(langTranslations).forEach(([key, translation]) => {
    // Match patterns like: key: 'English text',
    const regex = new RegExp(`(\\s*${key}:\\s*)'${key}'(,?)`, 'g')
    content = content.replace(regex, (match, before, after) => {
      changeCount++
      return `${before}'${translation}'${after}`
    })
  })
  
  // Update the comment to indicate partial translation
  content = content.replace(
    /\/\/ .+ translations - TO BE COMPLETED/,
    `// ${languageName} translations - PARTIAL TRANSLATION
// Many strings still need proper translation from English`
  )
  
  fs.writeFileSync(filePath, content)
  console.log(`✅ Partially translated ${languageName} (${language}.ts) - ${changeCount} strings translated`)
}

// Languages to translate
const languagesToTranslate = [
  { code: 'bg', name: 'Bulgarian' },
  { code: 'cs', name: 'Czech' },
  { code: 'da', name: 'Danish' },
  { code: 'et', name: 'Estonian' },
  { code: 'fi', name: 'Finnish' },
  { code: 'ga', name: 'Irish' },
  { code: 'hr', name: 'Croatian' },
  { code: 'hu', name: 'Hungarian' },
  { code: 'lt', name: 'Lithuanian' },
  { code: 'lv', name: 'Latvian' },
  { code: 'no', name: 'Norwegian' },
  { code: 'ro', name: 'Romanian' },
  { code: 'sk', name: 'Slovak' },
  { code: 'sl', name: 'Slovenian' }
]

console.log('Starting partial translation of new languages...\n')
console.log('NOTE: This provides only basic UI terms. Full translation requires a professional translation service.\n')

languagesToTranslate.forEach(({ code, name }) => {
  translateFile(code, name)
})

console.log('\n⚠️  IMPORTANT: These are partial translations with only basic UI terms.')
console.log('For production use, please use a professional translation service to translate all 457 strings properly.')
console.log('\nConsider using services like:')
console.log('- DeepL API (https://www.deepl.com/pro-api)')
console.log('- Google Cloud Translation API')
console.log('- Professional human translators')