name = "tiko-identity-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
account_id = "dc2b7d14a69351375cab6de9a13ddee9"
routes = [
  { pattern = "id.tiko.mt/*", zone_name = "tiko.mt" }
]

[vars]
IDENTITY_ALLOWED_ORIGINS = "https://tiko.mt,https://*.tiko.mt,https://tikoapps.org,https://*.tikoapps.org,https://development.tiko-*.pages.dev,http://localhost:3000,http://localhost:3008"
MAGIC_LINK_BASE_URL = "https://id.tiko.mt/api/identity/verify-magic-link"
ANONYMOUS_USER_RETENTION_DAYS = "7"

[triggers]
crons = ["0 3 * * *"]

[[d1_databases]]
binding = "IDENTITY_DB"
database_name = "tiko-identity"
database_id = "036a1726-ac16-48a9-ab76-22c3a88ca7ae"

[[kv_namespaces]]
binding = "IDENTITY_SESSION_CACHE"
id = "32bcc7c6d5074a95a1ea62ee772da3be"
preview_id = "32bcc7c6d5074a95a1ea62ee772da3be"

[[queues.producers]]
binding = "MAGIC_LINK_QUEUE"
queue = "tiko-magic-link-email"

[env.development.vars]
IDENTITY_ALLOWED_ORIGINS = "https://tikoapps.org,https://*.tikoapps.org,http://localhost:3000,http://localhost:3008"
MAGIC_LINK_BASE_URL = "https://tiko-identity-api-development.vandipyan.workers.dev/api/identity/verify-magic-link"
ANONYMOUS_USER_RETENTION_DAYS = "7"

[[env.development.d1_databases]]
binding = "IDENTITY_DB"
database_name = "tiko-identity"
database_id = "036a1726-ac16-48a9-ab76-22c3a88ca7ae"

[[env.development.kv_namespaces]]
binding = "IDENTITY_SESSION_CACHE"
id = "32bcc7c6d5074a95a1ea62ee772da3be"
preview_id = "32bcc7c6d5074a95a1ea62ee772da3be"

[[env.development.queues.producers]]
binding = "MAGIC_LINK_QUEUE"
queue = "tiko-magic-link-email"
