-- Insert default sound assets that are used by the apps
-- These correspond to the SOUNDS constant in usePlaySound.ts

INSERT INTO assets (
  id,
  title,
  description,
  filename,
  original_filename,
  file_path,
  file_size,
  mime_type,
  file_extension,
  categories,
  tags,
  is_public,
  user_id
) VALUES 
  (
    'c9a2b696-e9ad-4cd0-b8f5-f518a56bee2e',
    'Wrong Item Sound',
    'Sound effect played when user selects incorrect item in sequence',
    'wrong-item.mp3',
    'wrong-item.mp3',
    'audio/system/wrong-item.mp3',
    15420, -- Approximate file size in bytes
    'audio/mpeg',
    'mp3',
    ARRAY['system', 'feedback'],
    ARRAY['wrong', 'error', 'feedback', 'negative'],
    true, -- Public asset
    NULL -- System asset, no specific user
  ),
  (
    '0ab406c7-25f5-4663-872f-55990cf45904',
    'Plub Sound',
    'Plub sound effect',
    'plub.mp3',
    'plub.mp3', 
    'audio/system/plub.mp3',
    12800,
    'audio/mpeg',
    'mp3',
    ARRAY['system', 'effects'],
    ARRAY['plub', 'bubble', 'pop'],
    true,
    NULL
  ),
  (
    '0b60deeb-4ce2-4818-8c3f-671614dbbb6b',
    'Rocket Sound',
    'Rocket launch sound effect',
    'rocket.mp3',
    'rocket.mp3',
    'audio/system/rocket.mp3',
    24600,
    'audio/mpeg', 
    'mp3',
    ARRAY['system', 'effects'],
    ARRAY['rocket', 'launch', 'whoosh'],
    true,
    NULL
  ),
  (
    'a7109960-e3c0-46a7-a666-a7a1a02b6fd0',
    'Win Sound',
    'Success sound played when user completes a task',
    'win.mp3',
    'win.mp3',
    'audio/system/win.mp3',
    18950,
    'audio/mpeg',
    'mp3',
    ARRAY['system', 'feedback'], 
    ARRAY['win', 'success', 'complete', 'positive'],
    true,
    NULL
  ),
  (
    '4ab87e97-db4a-42bd-b137-a80f554b0367',
    'Zoof Sound',
    'Zoof sound effect',
    'zoof.mp3',
    'zoof.mp3',
    'audio/system/zoof.mp3',
    16200,
    'audio/mpeg',
    'mp3',
    ARRAY['system', 'effects'],
    ARRAY['zoof', 'swoosh', 'movement'],
    true,
    NULL
  ),
  (
    '362cf825-5fe8-427f-b259-a7dbfcf9d617',
    'Slurp Sound', 
    'Slurp sound effect',
    'slurp.mp3',
    'slurp.mp3',
    'audio/system/slurp.mp3',
    14700,
    'audio/mpeg',
    'mp3',
    ARRAY['system', 'effects'],
    ARRAY['slurp', 'drink', 'liquid'],
    true,
    NULL
  ),
  (
    '4393a16c-3f49-4b33-8ebc-5254bb55bef8',
    'Deny Sound',
    'Sound effect for denied or blocked actions',
    'deny.mp3', 
    'deny.mp3',
    'audio/system/deny.mp3',
    11500,
    'audio/mpeg',
    'mp3',
    ARRAY['system', 'feedback'],
    ARRAY['deny', 'block', 'negative', 'error'],
    true,
    NULL
  ),
  (
    '09e0367e-337f-49b2-b2e0-ec57e329d184',
    'Eheh Sound',
    'Eheh laugh sound effect',
    'eheh.mp3',
    'eheh.mp3', 
    'audio/system/eheh.mp3',
    13400,
    'audio/mpeg',
    'mp3',
    ARRAY['system', 'effects'],
    ARRAY['laugh', 'eheh', 'giggle'],
    true,
    NULL
  )
ON CONFLICT (id) DO NOTHING; -- Don't insert if already exists