name = "tiko-content-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# Production route is now configured via custom domain in Cloudflare dashboard
# content.tikoapi.org -> tiko-content-api worker

[env.staging]
routes = [
  { pattern = "content-staging.tikoapi.org/*", zone_name = "tikoapi.org" }
]

# KV namespace for caching
[[kv_namespaces]]
binding = "CONTENT_CACHE"
id = "19e053c7a4c94f16a1ee4a436bfac34a"

# Environment variables
[vars]
CACHE_TTL = "86400" # 24 hours in seconds
SUPABASE_URL = "https://kejvhvszhevfwgsztedf.supabase.co"

# Secret must be set as worker secret:
# In Cloudflare Dashboard: Workers & Pages > tiko-content-api > Settings > Variables
# Add Secret: SUPABASE_SECRET with the new Supabase secret key (sb_secret_...)

# Durable Objects for advanced caching (optional)
# [[durable_objects.bindings]]
# name = "CACHE_MANAGER"
# class_name = "CacheManager"

# R2 bucket for large content (optional)
# [[r2_buckets]]
# binding = "CONTENT_BUCKET"
# bucket_name = "tiko-content"