name: Deploy Websites to Cloudflare Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      target:
        description: 'Target website to deploy (marketing, or all)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - marketing
      message:
        description: 'Deployment message'
        required: false
        default: 'Manual deployment from admin dashboard'

jobs:
  check-triggers:
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.check.outputs.should-build }}
      build-marketing: ${{ steps.check.outputs.build-marketing }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - name: Check triggers
        id: check
        run: |
          # Default to no builds
          echo "should-build=false" >> $GITHUB_OUTPUT
          echo "build-marketing=false" >> $GITHUB_OUTPUT
          
          # Handle workflow_dispatch trigger
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TARGET="${{ github.event.inputs.target }}"
            echo "Workflow dispatch target: $TARGET"
            
            if [[ "$TARGET" == "all" ]] || [[ "$TARGET" == "marketing" ]]; then
              echo "should-build=true" >> $GITHUB_OUTPUT
              echo "build-marketing=true" >> $GITHUB_OUTPUT
            fi
            exit 0
          fi
          
          # Handle push trigger - check commit message
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          echo "Commit message: $COMMIT_MSG"
          
          # Check for build all triggers
          if [[ "$COMMIT_MSG" == *"[build:all]"* ]] || [[ "$COMMIT_MSG" == *"[build:websites]"* ]]; then
            echo "should-build=true" >> $GITHUB_OUTPUT
            echo "build-marketing=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check for specific website triggers
          if [[ "$COMMIT_MSG" == *"[build:marketing]"* ]]; then
            echo "build-marketing=true" >> $GITHUB_OUTPUT
            echo "should-build=true" >> $GITHUB_OUTPUT
          fi

  check-environment:
    needs: check-triggers
    if: needs.check-triggers.outputs.should-build == 'true'
    runs-on: ubuntu-latest
    name: Check Required Environment Variables
    steps:
      - name: Check Cloudflare API Token
        run: |
          if [ -z "${{ secrets.CLOUDFLARE_API_TOKEN }}" ]; then
            echo "❌ ERROR: Missing required secret CLOUDFLARE_API_TOKEN"
            echo "Please add this secret in GitHub Settings > Secrets and variables > Actions"
            exit 1
          fi
          echo "✅ CLOUDFLARE_API_TOKEN is configured"
      
      - name: Check Supabase Environment Variables
        run: |
          MISSING_VARS=""
          
          if [ -z "${{ secrets.VITE_SUPABASE_URL }}" ]; then
            MISSING_VARS="$MISSING_VARS VITE_SUPABASE_URL"
          fi
          
          if [ -z "${{ secrets.VITE_SUPABASE_ANON_KEY }}" ]; then
            MISSING_VARS="$MISSING_VARS VITE_SUPABASE_ANON_KEY"
          fi
          
          if [ -n "$MISSING_VARS" ]; then
            echo "❌ ERROR: Missing required Supabase secrets:"
            for var in $MISSING_VARS; do
              echo "  - $var"
            done
            echo ""
            echo "Please add these secrets in GitHub Settings > Secrets and variables > Actions"
            exit 1
          fi
          
          echo "✅ Supabase environment variables are configured"

  deploy-marketing:
    needs: [check-triggers, check-environment]
    if: needs.check-triggers.outputs.build-marketing == 'true'
    runs-on: ubuntu-latest
    name: Deploy Marketing Website
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Install Wrangler
        run: pnpm add -w wrangler@3.90.0 --save-dev
        
      - name: Generate i18n translations
        run: pnpm generate:i18n:worker:prod
        
      - name: Build Marketing website
        run: |
          pnpm --filter=@tiko/ui build
          pnpm --filter=@tiko/core build
          pnpm --filter=marketing exec vite build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_USE_CONTENT_WORKER: "true"
          VITE_CONTENT_API_URL: "https://content.tikoapi.org"
          VITE_DEPLOYED_VERSION_ID: "v1.0.1"
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: dc2b7d14a69351375cab6de9a13ddee9
          command: pages deploy ./websites/marketing/dist --project-name=tiko-marketing