name: Deploy Tools to Cloudflare Pages

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
    inputs:
      target:
        description: 'Target tool to deploy (admin, ui-docs, or all)'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - admin
          - ui-docs
      message:
        description: 'Deployment message'
        required: false
        default: 'Manual deployment from admin dashboard'

jobs:
  determine-environment:
    uses: ./.github/workflows/reusable-determine-environment.yml

  check-triggers:
    runs-on: ubuntu-latest
    outputs:
      should-build: ${{ steps.check.outputs.should-build }}
      build-admin: ${{ steps.check.outputs.build-admin }}
      build-ui-docs: ${{ steps.check.outputs.build-ui-docs }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          
      - name: Check triggers
        id: check
        run: |
          # Default to no builds
          echo "should-build=false" >> $GITHUB_OUTPUT
          echo "build-admin=false" >> $GITHUB_OUTPUT
          echo "build-ui-docs=false" >> $GITHUB_OUTPUT
          
          # Handle workflow_dispatch trigger
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            TARGET="${{ github.event.inputs.target }}"
            echo "Workflow dispatch target: $TARGET"
            
            if [[ "$TARGET" == "all" ]]; then
              echo "should-build=true" >> $GITHUB_OUTPUT
              echo "build-admin=true" >> $GITHUB_OUTPUT
              echo "build-ui-docs=true" >> $GITHUB_OUTPUT
            elif [[ "$TARGET" == "admin" ]]; then
              echo "build-admin=true" >> $GITHUB_OUTPUT
              echo "should-build=true" >> $GITHUB_OUTPUT
            elif [[ "$TARGET" == "ui-docs" ]]; then
              echo "build-ui-docs=true" >> $GITHUB_OUTPUT
              echo "should-build=true" >> $GITHUB_OUTPUT
            fi
            exit 0
          fi
          
          # For develop branch, check changed files instead of commit message
          if [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "Develop branch detected - checking changed files..."
            
            # Get list of changed files
            CHANGED_FILES=$(git diff --name-only HEAD^ HEAD || git diff --name-only HEAD)
            echo "Changed files:"
            echo "$CHANGED_FILES"
            
            # Check if UI or Core packages changed (deploy all tools)
            if echo "$CHANGED_FILES" | grep -E "^packages/(ui|core)/" > /dev/null; then
              echo "UI or Core package changed - deploying all tools"
              echo "should-build=true" >> $GITHUB_OUTPUT
              echo "build-admin=true" >> $GITHUB_OUTPUT
              echo "build-ui-docs=true" >> $GITHUB_OUTPUT
              exit 0
            fi
            
            # Check individual tools
            if echo "$CHANGED_FILES" | grep -E "^tools/admin/" > /dev/null; then
              echo "build-admin=true" >> $GITHUB_OUTPUT
              echo "should-build=true" >> $GITHUB_OUTPUT
            fi
            if echo "$CHANGED_FILES" | grep -E "^tools/ui-docs/" > /dev/null; then
              echo "build-ui-docs=true" >> $GITHUB_OUTPUT
              echo "should-build=true" >> $GITHUB_OUTPUT
            fi
            
            exit 0
          fi

          # For master branch, handle push trigger - check commit message
          COMMIT_MSG='${{ github.event.head_commit.message }}'
          echo "Commit message: $COMMIT_MSG"
          
          # Check for build all triggers
          if [[ "$COMMIT_MSG" == *"[build:all]"* ]] || [[ "$COMMIT_MSG" == *"[build:tools]"* ]]; then
            echo "should-build=true" >> $GITHUB_OUTPUT
            echo "build-admin=true" >> $GITHUB_OUTPUT
            echo "build-ui-docs=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          
          # Check for specific tool triggers
          if [[ "$COMMIT_MSG" == *"[build:admin]"* ]]; then
            echo "build-admin=true" >> $GITHUB_OUTPUT
            echo "should-build=true" >> $GITHUB_OUTPUT
          fi
          if [[ "$COMMIT_MSG" == *"[build:ui-docs]"* ]]; then
            echo "build-ui-docs=true" >> $GITHUB_OUTPUT
            echo "should-build=true" >> $GITHUB_OUTPUT
          fi

  check-environment:
    needs: check-triggers
    if: needs.check-triggers.outputs.should-build == 'true'
    uses: ./.github/workflows/reusable-check-environment.yml

  deploy-admin:
    needs: [determine-environment, check-triggers, check-environment]
    if: needs.check-triggers.outputs.build-admin == 'true'
    runs-on: ubuntu-latest
    name: Deploy Admin Tool (${{ needs.determine-environment.outputs.environment }})
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Build Admin tool
        run: |
          pnpm --filter=@tiko/ui build
          pnpm --filter=@tiko/core build
          pnpm --filter=admin build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
          VITE_SITE_URL: https://admin.tikoapps.org
      
      - name: Install Wrangler
        run: npm install -g wrangler
        
      - name: Create Pages project if needed
        run: |
          wrangler pages project create tiko-admin --production-branch=master || echo "Project already exists"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: dc2b7d14a69351375cab6de9a13ddee9
          
      - name: Deploy to Cloudflare Pages
        run: |
          PROJECT_NAME="tiko-admin${{ needs.determine-environment.outputs.branch-suffix }}"
          wrangler pages project create $PROJECT_NAME --production-branch=${{ github.ref_name }} || echo "Project already exists"
          wrangler pages deploy ./tools/admin/dist --project-name=$PROJECT_NAME --branch=${{ github.ref_name }}
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: dc2b7d14a69351375cab6de9a13ddee9

  deploy-ui-docs:
    needs: [determine-environment, check-triggers, check-environment]
    if: needs.check-triggers.outputs.build-ui-docs == 'true'
    runs-on: ubuntu-latest
    name: Deploy UI Docs (${{ needs.determine-environment.outputs.environment }})
    steps:
      - uses: actions/checkout@v4
      
      - uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        
      - name: Build UI Docs
        run: |
          pnpm --filter=@tiko/ui build
          pnpm --filter=@tiko/ui-docs build
          
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: dc2b7d14a69351375cab6de9a13ddee9
          command: pages deploy ./tools/ui-docs/dist --project-name=tiko-ui-docs${{ needs.determine-environment.outputs.branch-suffix }} --compatibility-date=2024-08-02 --branch=${{ github.ref_name }}